// Games data embedded directly in JavaScript
// This file is automatically generated from generated_games.json
// Generated on: 2025-11-08T16:13:21.360786
// Total games: 526

const GAMES_DATABASE = {
  "action": [
    {
      "name": "GTA Simulator",
      "file": "games/action/gta-simulator.html",
      "classification": "action",
      "filename": "gta-simulator"
    },
    {
      "name": "Masked Special Forces",
      "file": "games/action/masked-special-forces.html",
      "classification": "action",
      "filename": "masked-special-forces"
    },
    {
      "name": "Five Nights At Freddys",
      "file": "games/action/five-nights-at-freddys.html",
      "classification": "action",
      "filename": "five-nights-at-freddys"
    },
    {
      "name": "Geometry Arrow",
      "file": "games/action/geometry-arrow.html",
      "classification": "action",
      "filename": "geometry-arrow"
    },
    {
      "name": "Moto Road Rash 3D",
      "file": "games/action/moto-road-rash-3d.html",
      "classification": "action",
      "filename": "moto-road-rash-3d"
    },
    {
      "name": "Fragen",
      "file": "games/action/fragen.html",
      "classification": "action",
      "filename": "fragen"
    },
    {
      "name": "Extreme Run 3D",
      "file": "games/action/extreme-run-3d.html",
      "classification": "action",
      "filename": "extreme-run-3d"
    },
    {
      "name": "Stickman GTA City",
      "file": "games/action/stickman-gta-city.html",
      "classification": "action",
      "filename": "stickman-gta-city"
    },
    {
      "name": "Five Nights At Freddy's 2",
      "file": "games/action/five-nights-at-freddys-2.html",
      "classification": "action",
      "filename": "five-nights-at-freddys-2"
    },
    {
      "name": "Stickman Parkour",
      "file": "games/action/stickman-parkour.html",
      "classification": "action",
      "filename": "stickman-parkour"
    },
    {
      "name": "Stick Fighter 3D",
      "file": "games/action/stick-fighter-3d.html",
      "classification": "action",
      "filename": "stick-fighter-3d"
    },
    {
      "name": "DTA 6",
      "file": "games/action/dta-6.html",
      "classification": "action",
      "filename": "dta-6"
    },
    {
      "name": "Get On Top",
      "file": "games/action/get-on-top.html",
      "classification": "action",
      "filename": "get-on-top"
    },
    {
      "name": "Aventador Vice Crime City",
      "file": "games/action/aventador-vice-crime-city.html",
      "classification": "action",
      "filename": "aventador-vice-crime-city"
    },
    {
      "name": "Red Light Green Light",
      "file": "games/action/red-light-green-light.html",
      "classification": "action",
      "filename": "red-light-green-light"
    },
    {
      "name": "FPS Simulator",
      "file": "games/action/fps-simulator.html",
      "classification": "action",
      "filename": "fps-simulator"
    },
    {
      "name": "Crazy Strike Force",
      "file": "games/action/crazy-strike-force.html",
      "classification": "action",
      "filename": "crazy-strike-force"
    },
    {
      "name": "CS Online",
      "file": "games/action/cs-online.html",
      "classification": "action",
      "filename": "cs-online"
    },
    {
      "name": "Guerrillas io",
      "file": "games/action/guerrillas-io.html",
      "classification": "action",
      "filename": "guerrillas-io"
    },
    {
      "name": "Drunken Duel",
      "file": "games/action/drunken-duel.html",
      "classification": "action",
      "filename": "drunken-duel"
    },
    {
      "name": "Only Up Obby",
      "file": "games/action/only-up-obby.html",
      "classification": "action",
      "filename": "only-up-obby"
    },
    {
      "name": "Dan the Man",
      "file": "games/action/dan-the-man.html",
      "classification": "action",
      "filename": "dan-the-man"
    },
    {
      "name": "Five Nights At Freddy's 4",
      "file": "games/action/five-nights-at-freddys-4.html",
      "classification": "action",
      "filename": "five-nights-at-freddys-4"
    },
    {
      "name": "Legendary Sniper",
      "file": "games/action/legendary-sniper.html",
      "classification": "action",
      "filename": "legendary-sniper"
    },
    {
      "name": "Five Nights At Freddy's 3",
      "file": "games/action/five-nights-at-freddys-3.html",
      "classification": "action",
      "filename": "five-nights-at-freddys-3"
    },
    {
      "name": "ShooterZ.io",
      "file": "games/action/shooterzio.html",
      "classification": "action",
      "filename": "shooterzio"
    },
    {
      "name": "Obby Prison Escape",
      "file": "games/action/obby-prison-escape.html",
      "classification": "action",
      "filename": "obby-prison-escape"
    },
    {
      "name": "WarStrike",
      "file": "games/action/warstrike.html",
      "classification": "action",
      "filename": "warstrike"
    },
    {
      "name": "Crazy Shooters 2",
      "file": "games/action/crazy-shooters-2.html",
      "classification": "action",
      "filename": "crazy-shooters-2"
    },
    {
      "name": "Archer Hero",
      "file": "games/action/archer-hero.html",
      "classification": "action",
      "filename": "archer-hero"
    },
    {
      "name": "Crazy Shooters",
      "file": "games/action/crazy-shooters.html",
      "classification": "action",
      "filename": "crazy-shooters"
    },
    {
      "name": "Funny Blade and Magic",
      "file": "games/action/funny-blade-and-magic.html",
      "classification": "action",
      "filename": "funny-blade-and-magic"
    },
    {
      "name": "Crazy Motorcycle",
      "file": "games/action/crazy-motorcycle.html",
      "classification": "action",
      "filename": "crazy-motorcycle"
    },
    {
      "name": "Snow Rider 3D",
      "file": "games/action/snow-rider-3d.html",
      "classification": "action",
      "filename": "snow-rider-3d"
    },
    {
      "name": "Slope Rolling",
      "file": "games/action/slope-rolling.html",
      "classification": "action",
      "filename": "slope-rolling"
    },
    {
      "name": "Mob City",
      "file": "games/action/mob-city.html",
      "classification": "action",
      "filename": "mob-city"
    },
    {
      "name": "Granny 2",
      "file": "games/action/granny-2.html",
      "classification": "action",
      "filename": "granny-2"
    },
    {
      "name": "Time Shooter 3: SWAT",
      "file": "games/action/time-shooter-3-swat.html",
      "classification": "action",
      "filename": "time-shooter-3-swat"
    },
    {
      "name": "Time Shooter 2",
      "file": "games/action/time-shooter-2.html",
      "classification": "action",
      "filename": "time-shooter-2"
    },
    {
      "name": "Pixel Survival",
      "file": "games/action/pixel-survival.html",
      "classification": "action",
      "filename": "pixel-survival"
    },
    {
      "name": "ArmedForces.io",
      "file": "games/action/armedforcesio.html",
      "classification": "action",
      "filename": "armedforcesio"
    },
    {
      "name": "Vex 3",
      "file": "games/action/vex-3.html",
      "classification": "action",
      "filename": "vex-3"
    },
    {
      "name": "Obby: Parkour Lava",
      "file": "games/action/obby-parkour-lava.html",
      "classification": "action",
      "filename": "obby-parkour-lava"
    },
    {
      "name": "FPS Strike",
      "file": "games/action/fps-strike.html",
      "classification": "action",
      "filename": "fps-strike"
    },
    {
      "name": "FNaF Shooter",
      "file": "games/action/fnaf-shooter.html",
      "classification": "action",
      "filename": "fnaf-shooter"
    },
    {
      "name": "Realistic Zombie Survival Warfare",
      "file": "games/action/realistic-zombie-survival-warfare.html",
      "classification": "action",
      "filename": "realistic-zombie-survival-warfare"
    },
    {
      "name": "Immortal: Dark Slayer",
      "file": "games/action/immortal-dark-slayer.html",
      "classification": "action",
      "filename": "immortal-dark-slayer"
    },
    {
      "name": "Funny Shooter 2",
      "file": "games/action/funny-shooter-2.html",
      "classification": "action",
      "filename": "funny-shooter-2"
    },
    {
      "name": "Geometry Vibes X-Ball",
      "file": "games/action/geometry-vibes-x-ball.html",
      "classification": "action",
      "filename": "geometry-vibes-x-ball"
    },
    {
      "name": "Zombie Apocalypse Shooter",
      "file": "games/action/zombie-apocalypse-shooter.html",
      "classification": "action",
      "filename": "zombie-apocalypse-shooter"
    },
    {
      "name": "Ultimate Robo Duel 3D",
      "file": "games/action/ultimate-robo-duel-3d.html",
      "classification": "action",
      "filename": "ultimate-robo-duel-3d"
    },
    {
      "name": "Hero Rush Tower Defense",
      "file": "games/action/hero-rush-tower-defense.html",
      "classification": "action",
      "filename": "hero-rush-tower-defense"
    },
    {
      "name": "Masked Forces Crazy Mode",
      "file": "games/action/masked-forces-crazy-mode.html",
      "classification": "action",
      "filename": "masked-forces-crazy-mode"
    },
    {
      "name": "Secret Sniper Agent",
      "file": "games/action/secret-sniper-agent.html",
      "classification": "action",
      "filename": "secret-sniper-agent"
    },
    {
      "name": "Time Shooter",
      "file": "games/action/time-shooter.html",
      "classification": "action",
      "filename": "time-shooter"
    },
    {
      "name": "Skibidi Toilet Shooting",
      "file": "games/action/skibidi-toilet-shooting.html",
      "classification": "action",
      "filename": "skibidi-toilet-shooting"
    },
    {
      "name": "Su Battle Royale",
      "file": "games/action/su-battle-royale.html",
      "classification": "action",
      "filename": "su-battle-royale"
    },
    {
      "name": "Tank War Simulator",
      "file": "games/action/tank-war-simulator.html",
      "classification": "action",
      "filename": "tank-war-simulator"
    },
    {
      "name": "Wasteland Shooters",
      "file": "games/action/wasteland-shooters.html",
      "classification": "action",
      "filename": "wasteland-shooters"
    },
    {
      "name": "Rebel Forces",
      "file": "games/action/rebel-forces.html",
      "classification": "action",
      "filename": "rebel-forces"
    },
    {
      "name": "Run Away 3",
      "file": "games/action/run-away-3.html",
      "classification": "action",
      "filename": "run-away-3"
    },
    {
      "name": "Monster Survivors",
      "file": "games/action/monster-survivors.html",
      "classification": "action",
      "filename": "monster-survivors"
    },
    {
      "name": "Rome Simulator",
      "file": "games/action/rome-simulator.html",
      "classification": "action",
      "filename": "rome-simulator"
    },
    {
      "name": "Horse Riding Simulator",
      "file": "games/action/horse-riding-simulator.html",
      "classification": "action",
      "filename": "horse-riding-simulator"
    },
    {
      "name": "City Police Cars",
      "file": "games/action/city-police-cars.html",
      "classification": "action",
      "filename": "city-police-cars"
    },
    {
      "name": "Airplane Racer",
      "file": "games/action/airplane-racer.html",
      "classification": "action",
      "filename": "airplane-racer"
    },
    {
      "name": "Dark Ninja Hanjo",
      "file": "games/action/dark-ninja-hanjo.html",
      "classification": "action",
      "filename": "dark-ninja-hanjo"
    },
    {
      "name": "Bob the Robber",
      "file": "games/action/bob-the-robber.html",
      "classification": "action",
      "filename": "bob-the-robber"
    },
    {
      "name": "Five Nights At Cat Freddy",
      "file": "games/action/five-nights-at-cat-freddy.html",
      "classification": "action",
      "filename": "five-nights-at-cat-freddy"
    },
    {
      "name": "Dragon Simulator Multiplayer",
      "file": "games/action/dragon-simulator-multiplayer.html",
      "classification": "action",
      "filename": "dragon-simulator-multiplayer"
    },
    {
      "name": "Gangsters",
      "file": "games/action/gangsters.html",
      "classification": "action",
      "filename": "gangsters"
    },
    {
      "name": "Tank Arena",
      "file": "games/action/tank-arena.html",
      "classification": "action",
      "filename": "tank-arena"
    },
    {
      "name": "Squid Shooter",
      "file": "games/action/squid-shooter.html",
      "classification": "action",
      "filename": "squid-shooter"
    },
    {
      "name": "Alien Sky Invasion",
      "file": "games/action/alien-sky-invasion.html",
      "classification": "action",
      "filename": "alien-sky-invasion"
    },
    {
      "name": "Five Nights At Candy's",
      "file": "games/action/five-nights-at-candys.html",
      "classification": "action",
      "filename": "five-nights-at-candys"
    },
    {
      "name": "Rainbow Obby Parkour",
      "file": "games/action/rainbow-obby-parkour.html",
      "classification": "action",
      "filename": "rainbow-obby-parkour"
    },
    {
      "name": "Horror Granny",
      "file": "games/action/horror-granny.html",
      "classification": "action",
      "filename": "horror-granny"
    },
    {
      "name": "Army Combat",
      "file": "games/action/army-combat.html",
      "classification": "action",
      "filename": "army-combat"
    },
    {
      "name": "Only Up Parkour",
      "file": "games/action/only-up-parkour.html",
      "classification": "action",
      "filename": "only-up-parkour"
    },
    {
      "name": "Pixel Path",
      "file": "games/action/pixel-path.html",
      "classification": "action",
      "filename": "pixel-path"
    },
    {
      "name": "Unpacking",
      "file": "games/action/unpacking.html",
      "classification": "action",
      "filename": "unpacking"
    },
    {
      "name": "Gummy Blocks",
      "file": "games/action/gummy-blocks.html",
      "classification": "action",
      "filename": "gummy-blocks"
    },
    {
      "name": "Bloxorz",
      "file": "games/action/bloxorz.html",
      "classification": "action",
      "filename": "bloxorz"
    },
    {
      "name": "Tic Tac Toe",
      "file": "games/action/tic-tac-toe.html",
      "classification": "action",
      "filename": "tic-tac-toe"
    },
    {
      "name": "Fireboy and Watergirl 2: Light Temple",
      "file": "games/action/fireboy-and-watergirl-2-light-temple.html",
      "classification": "action",
      "filename": "fireboy-and-watergirl-2-light-temple"
    },
    {
      "name": "Block Blast",
      "file": "games/action/block-blast.html",
      "classification": "action",
      "filename": "block-blast"
    },
    {
      "name": "Rummikub",
      "file": "games/action/rummikub.html",
      "classification": "action",
      "filename": "rummikub"
    },
    {
      "name": "Nuts and Bolts Puzzle",
      "file": "games/action/nuts-and-bolts-puzzle.html",
      "classification": "action",
      "filename": "nuts-and-bolts-puzzle"
    },
    {
      "name": "Fireboy and Watergirl 5: Elements",
      "file": "games/action/fireboy-and-watergirl-5-elements.html",
      "classification": "action",
      "filename": "fireboy-and-watergirl-5-elements"
    },
    {
      "name": "Fireboy and Watergirl 4: Crystal Temple",
      "file": "games/action/fireboy-and-watergirl-4-crystal-temple.html",
      "classification": "action",
      "filename": "fireboy-and-watergirl-4-crystal-temple"
    },
    {
      "name": "Charge It",
      "file": "games/action/charge-it.html",
      "classification": "action",
      "filename": "charge-it"
    },
    {
      "name": "Tetris",
      "file": "games/action/tetris.html",
      "classification": "action",
      "filename": "tetris"
    },
    {
      "name": "Fireboy and Watergirl 6: Fairy Tales",
      "file": "games/action/fireboy-and-watergirl-6-fairy-tales.html",
      "classification": "action",
      "filename": "fireboy-and-watergirl-6-fairy-tales"
    },
    {
      "name": "Obby: Draw and Jump",
      "file": "games/action/obby-draw-and-jump.html",
      "classification": "action",
      "filename": "obby-draw-and-jump"
    },
    {
      "name": "Fireboy and Watergirl 3: Ice Temple",
      "file": "games/action/fireboy-and-watergirl-3-ice-temple.html",
      "classification": "action",
      "filename": "fireboy-and-watergirl-3-ice-temple"
    },
    {
      "name": "Draw The Bridge",
      "file": "games/action/draw-the-bridge.html",
      "classification": "action",
      "filename": "draw-the-bridge"
    },
    {
      "name": "Global Guesser",
      "file": "games/action/global-guesser.html",
      "classification": "action",
      "filename": "global-guesser"
    },
    {
      "name": "Baby Doll House Cleaning",
      "file": "games/action/baby-doll-house-cleaning.html",
      "classification": "action",
      "filename": "baby-doll-house-cleaning"
    },
    {
      "name": "Soccer Merge",
      "file": "games/action/soccer-merge.html",
      "classification": "action",
      "filename": "soccer-merge"
    },
    {
      "name": "Mini Cars Racing",
      "file": "games/action/mini-cars-racing.html",
      "classification": "action",
      "filename": "mini-cars-racing"
    },
    {
      "name": "Super Mini Racing",
      "file": "games/action/super-mini-racing.html",
      "classification": "action",
      "filename": "super-mini-racing"
    },
    {
      "name": "2 Player Crazy Racer",
      "file": "games/action/2-player-crazy-racer.html",
      "classification": "action",
      "filename": "2-player-crazy-racer"
    },
    {
      "name": "Hurakan City Driver HD",
      "file": "games/action/hurakan-city-driver-hd.html",
      "classification": "action",
      "filename": "hurakan-city-driver-hd"
    },
    {
      "name": "Free City Drive",
      "file": "games/action/free-city-drive.html",
      "classification": "action",
      "filename": "free-city-drive"
    },
    {
      "name": "Burnout Crazy Drift",
      "file": "games/action/burnout-crazy-drift.html",
      "classification": "action",
      "filename": "burnout-crazy-drift"
    },
    {
      "name": "Tag Run",
      "file": "games/action/tag-run.html",
      "classification": "action",
      "filename": "tag-run"
    },
    {
      "name": "Geometry Vibes 3D",
      "file": "games/action/geometry-vibes-3d.html",
      "classification": "action",
      "filename": "geometry-vibes-3d"
    },
    {
      "name": "Geometry Vibes",
      "file": "games/action/geometry-vibes.html",
      "classification": "action",
      "filename": "geometry-vibes"
    },
    {
      "name": "Basketball Stars",
      "file": "games/action/basketball-stars.html",
      "classification": "action",
      "filename": "basketball-stars"
    },
    {
      "name": "Paper io 2",
      "file": "games/action/paper-io-2.html",
      "classification": "action",
      "filename": "paper-io-2"
    },
    {
      "name": "Brainrot Clicker",
      "file": "games/action/brainrot-clicker.html",
      "classification": "action",
      "filename": "brainrot-clicker"
    },
    {
      "name": "Obby Gym Simulator",
      "file": "games/action/obby-gym-simulator.html",
      "classification": "action",
      "filename": "obby-gym-simulator"
    },
    {
      "name": "Geometry Vibes Monster",
      "file": "games/action/geometry-vibes-monster.html",
      "classification": "action",
      "filename": "geometry-vibes-monster"
    },
    {
      "name": "Waterpark Slide io",
      "file": "games/action/waterpark-slide-io.html",
      "classification": "action",
      "filename": "waterpark-slide-io"
    },
    {
      "name": "Chess",
      "file": "games/action/chess.html",
      "classification": "action",
      "filename": "chess"
    },
    {
      "name": "Blocky Combat Swat",
      "file": "games/action/blocky-combat-swat.html",
      "classification": "action",
      "filename": "blocky-combat-swat"
    },
    {
      "name": "8 Ball Pool Billiard",
      "file": "games/action/8-ball-pool-billiard.html",
      "classification": "action",
      "filename": "8-ball-pool-billiard"
    },
    {
      "name": "Hole io",
      "file": "games/action/hole-io.html",
      "classification": "action",
      "filename": "hole-io"
    },
    {
      "name": "Guess the Italian Brainrot Animals",
      "file": "games/action/guess-the-italian-brainrot-animals.html",
      "classification": "action",
      "filename": "guess-the-italian-brainrot-animals"
    },
    {
      "name": "State.io",
      "file": "games/action/stateio.html",
      "classification": "action",
      "filename": "stateio"
    },
    {
      "name": "Xtreme Paintball Wars",
      "file": "games/action/xtreme-paintball-wars.html",
      "classification": "action",
      "filename": "xtreme-paintball-wars"
    },
    {
      "name": "Halloween Survival",
      "file": "games/action/halloween-survival.html",
      "classification": "action",
      "filename": "halloween-survival"
    },
    {
      "name": "CobraZ.io Classic",
      "file": "games/action/cobrazio-classic.html",
      "classification": "action",
      "filename": "cobrazio-classic"
    },
    {
      "name": "ForceZ.io",
      "file": "games/action/forcezio.html",
      "classification": "action",
      "filename": "forcezio"
    },
    {
      "name": "Survival Karts",
      "file": "games/action/survival-karts.html",
      "classification": "action",
      "filename": "survival-karts"
    },
    {
      "name": "Rummy Multiplayer",
      "file": "games/action/rummy-multiplayer.html",
      "classification": "action",
      "filename": "rummy-multiplayer"
    },
    {
      "name": "Dragon World",
      "file": "games/action/dragon-world.html",
      "classification": "action",
      "filename": "dragon-world"
    },
    {
      "name": "Masked Forces Zombie Survival",
      "file": "games/action/masked-forces-zombie-survival.html",
      "classification": "action",
      "filename": "masked-forces-zombie-survival"
    },
    {
      "name": "Masked Shooters Assault",
      "file": "games/action/masked-shooters-assault.html",
      "classification": "action",
      "filename": "masked-shooters-assault"
    },
    {
      "name": "Masked io",
      "file": "games/action/masked-io.html",
      "classification": "action",
      "filename": "masked-io"
    },
    {
      "name": "Bandits Multiplayer PvP",
      "file": "games/action/bandits-multiplayer-pvp.html",
      "classification": "action",
      "filename": "bandits-multiplayer-pvp"
    },
    {
      "name": "Mech Shooter",
      "file": "games/action/mech-shooter.html",
      "classification": "action",
      "filename": "mech-shooter"
    },
    {
      "name": "Masked Forces",
      "file": "games/action/masked-forces.html",
      "classification": "action",
      "filename": "masked-forces"
    },
    {
      "name": "Gigga io",
      "file": "games/action/gigga-io.html",
      "classification": "action",
      "filename": "gigga-io"
    },
    {
      "name": "Subway Clash 2",
      "file": "games/action/subway-clash-2.html",
      "classification": "action",
      "filename": "subway-clash-2"
    },
    {
      "name": "Jul Moto RacingÂ",
      "file": "games/action/jul-moto-racingâ.html",
      "classification": "action",
      "filename": "jul-moto-racingâ"
    },
    {
      "name": "War of Ships io",
      "file": "games/action/war-of-ships-io.html",
      "classification": "action",
      "filename": "war-of-ships-io"
    },
    {
      "name": "Basketball io",
      "file": "games/action/basketball-io.html",
      "classification": "action",
      "filename": "basketball-io"
    },
    {
      "name": "Void City io",
      "file": "games/action/void-city-io.html",
      "classification": "action",
      "filename": "void-city-io"
    },
    {
      "name": "Basketball King",
      "file": "games/action/basketball-king.html",
      "classification": "action",
      "filename": "basketball-king"
    },
    {
      "name": "Skibidi Toilet io",
      "file": "games/action/skibidi-toilet-io.html",
      "classification": "action",
      "filename": "skibidi-toilet-io"
    },
    {
      "name": "Cute Snake io",
      "file": "games/action/cute-snake-io.html",
      "classification": "action",
      "filename": "cute-snake-io"
    },
    {
      "name": "Slide io",
      "file": "games/action/slide-io.html",
      "classification": "action",
      "filename": "slide-io"
    },
    {
      "name": "Paper Planets",
      "file": "games/action/paper-planets.html",
      "classification": "action",
      "filename": "paper-planets"
    },
    {
      "name": "State io Wars",
      "file": "games/action/state-io-wars.html",
      "classification": "action",
      "filename": "state-io-wars"
    },
    {
      "name": "Dont Fall io",
      "file": "games/action/dont-fall-io.html",
      "classification": "action",
      "filename": "dont-fall-io"
    },
    {
      "name": "Kings io",
      "file": "games/action/kings-io.html",
      "classification": "action",
      "filename": "kings-io"
    },
    {
      "name": "Snow War io",
      "file": "games/action/snow-war-io.html",
      "classification": "action",
      "filename": "snow-war-io"
    },
    {
      "name": "Dino Evolution io",
      "file": "games/action/dino-evolution-io.html",
      "classification": "action",
      "filename": "dino-evolution-io"
    },
    {
      "name": "Agar.io",
      "file": "games/action/agario.html",
      "classification": "action",
      "filename": "agario"
    },
    {
      "name": "Mini Shooters",
      "file": "games/action/mini-shooters.html",
      "classification": "action",
      "filename": "mini-shooters"
    },
    {
      "name": "Trains io",
      "file": "games/action/trains-io.html",
      "classification": "action",
      "filename": "trains-io"
    },
    {
      "name": "Snake Wars",
      "file": "games/action/snake-wars.html",
      "classification": "action",
      "filename": "snake-wars"
    },
    {
      "name": "SwordBattle io",
      "file": "games/action/swordbattle-io.html",
      "classification": "action",
      "filename": "swordbattle-io"
    },
    {
      "name": "Social Media Snake",
      "file": "games/action/social-media-snake.html",
      "classification": "action",
      "filename": "social-media-snake"
    },
    {
      "name": "ToonZ io",
      "file": "games/action/toonz-io.html",
      "classification": "action",
      "filename": "toonz-io"
    },
    {
      "name": "Arena Wars io",
      "file": "games/action/arena-wars-io.html",
      "classification": "action",
      "filename": "arena-wars-io"
    },
    {
      "name": "Love Tester",
      "file": "games/action/love-tester.html",
      "classification": "action",
      "filename": "love-tester"
    },
    {
      "name": "TB World",
      "file": "games/action/tb-world.html",
      "classification": "action",
      "filename": "tb-world"
    },
    {
      "name": "Italian Brainrot Clicker",
      "file": "games/action/italian-brainrot-clicker.html",
      "classification": "action",
      "filename": "italian-brainrot-clicker"
    },
    {
      "name": "Papa's Scooperia",
      "file": "games/action/papas-scooperia.html",
      "classification": "action",
      "filename": "papas-scooperia"
    },
    {
      "name": "Elastic Man",
      "file": "games/action/elastic-man.html",
      "classification": "action",
      "filename": "elastic-man"
    },
    {
      "name": "Papa's Freezeria",
      "file": "games/action/papas-freezeria.html",
      "classification": "action",
      "filename": "papas-freezeria"
    },
    {
      "name": "Papa's Pastaria",
      "file": "games/action/papas-pastaria.html",
      "classification": "action",
      "filename": "papas-pastaria"
    },
    {
      "name": "Papa's Cheeseria",
      "file": "games/action/papas-cheeseria.html",
      "classification": "action",
      "filename": "papas-cheeseria"
    },
    {
      "name": "Uno Online",
      "file": "games/action/uno-online.html",
      "classification": "action",
      "filename": "uno-online"
    },
    {
      "name": "Pill Soccer",
      "file": "games/action/pill-soccer.html",
      "classification": "action",
      "filename": "pill-soccer"
    },
    {
      "name": "Barbiemania",
      "file": "games/action/barbiemania.html",
      "classification": "action",
      "filename": "barbiemania"
    },
    {
      "name": "Papa's Wingeria",
      "file": "games/action/papas-wingeria.html",
      "classification": "action",
      "filename": "papas-wingeria"
    },
    {
      "name": "Head Soccer 2022",
      "file": "games/action/head-soccer-2022.html",
      "classification": "action",
      "filename": "head-soccer-2022"
    },
    {
      "name": "Cat Girl Fashion Challenge",
      "file": "games/action/cat-girl-fashion-challenge.html",
      "classification": "action",
      "filename": "cat-girl-fashion-challenge"
    },
    {
      "name": "Princess Wedding",
      "file": "games/action/princess-wedding.html",
      "classification": "action",
      "filename": "princess-wedding"
    },
    {
      "name": "Papa's Bakeria",
      "file": "games/action/papas-bakeria.html",
      "classification": "action",
      "filename": "papas-bakeria"
    },
    {
      "name": "Organize It",
      "file": "games/action/organize-it.html",
      "classification": "action",
      "filename": "organize-it"
    },
    {
      "name": "Papa's Sushiria",
      "file": "games/action/papas-sushiria.html",
      "classification": "action",
      "filename": "papas-sushiria"
    },
    {
      "name": "LOL Surprise Style Studio",
      "file": "games/action/lol-surprise-style-studio.html",
      "classification": "action",
      "filename": "lol-surprise-style-studio"
    },
    {
      "name": "Julie Beauty Salon",
      "file": "games/action/julie-beauty-salon.html",
      "classification": "action",
      "filename": "julie-beauty-salon"
    },
    {
      "name": "Tiny Fishing",
      "file": "games/action/tiny-fishing.html",
      "classification": "action",
      "filename": "tiny-fishing"
    },
    {
      "name": "Wedding Beauty Salon",
      "file": "games/action/wedding-beauty-salon.html",
      "classification": "action",
      "filename": "wedding-beauty-salon"
    },
    {
      "name": "Kikis Pink Christmas",
      "file": "games/action/kikis-pink-christmas.html",
      "classification": "action",
      "filename": "kikis-pink-christmas"
    },
    {
      "name": "BFFs Black Friday Collection",
      "file": "games/action/bffs-black-friday-collection.html",
      "classification": "action",
      "filename": "bffs-black-friday-collection"
    },
    {
      "name": "Snake Football",
      "file": "games/action/snake-football.html",
      "classification": "action",
      "filename": "snake-football"
    },
    {
      "name": "Papa's Cupcakeria",
      "file": "games/action/papas-cupcakeria.html",
      "classification": "action",
      "filename": "papas-cupcakeria"
    },
    {
      "name": "Papa's Hot Doggeria",
      "file": "games/action/papas-hot-doggeria.html",
      "classification": "action",
      "filename": "papas-hot-doggeria"
    },
    {
      "name": "Shopping Mania",
      "file": "games/action/shopping-mania.html",
      "classification": "action",
      "filename": "shopping-mania"
    },
    {
      "name": "Wedding Planner",
      "file": "games/action/wedding-planner.html",
      "classification": "action",
      "filename": "wedding-planner"
    },
    {
      "name": "Fun Party Makeup",
      "file": "games/action/fun-party-makeup.html",
      "classification": "action",
      "filename": "fun-party-makeup"
    },
    {
      "name": "Papa's Burgeria",
      "file": "games/action/papas-burgeria.html",
      "classification": "action",
      "filename": "papas-burgeria"
    },
    {
      "name": "Little Unicorn",
      "file": "games/action/little-unicorn.html",
      "classification": "action",
      "filename": "little-unicorn"
    },
    {
      "name": "Four Colors",
      "file": "games/action/four-colors.html",
      "classification": "action",
      "filename": "four-colors"
    },
    {
      "name": "Snake",
      "file": "games/action/snake.html",
      "classification": "action",
      "filename": "snake"
    },
    {
      "name": "BTS Signature Fashion Style",
      "file": "games/action/bts-signature-fashion-style.html",
      "classification": "action",
      "filename": "bts-signature-fashion-style"
    },
    {
      "name": "Papa's Pancakeria",
      "file": "games/action/papas-pancakeria.html",
      "classification": "action",
      "filename": "papas-pancakeria"
    },
    {
      "name": "Angela All Season Fashion",
      "file": "games/action/angela-all-season-fashion.html",
      "classification": "action",
      "filename": "angela-all-season-fashion"
    },
    {
      "name": "Papa's Pizzeria",
      "file": "games/action/papas-pizzeria.html",
      "classification": "action",
      "filename": "papas-pizzeria"
    },
    {
      "name": "Monster Girls Back to School",
      "file": "games/action/monster-girls-back-to-school.html",
      "classification": "action",
      "filename": "monster-girls-back-to-school"
    },
    {
      "name": "Princess Influencer Salon",
      "file": "games/action/princess-influencer-salon.html",
      "classification": "action",
      "filename": "princess-influencer-salon"
    },
    {
      "name": "BFFs Retro Time Travel Fashion",
      "file": "games/action/bffs-retro-time-travel-fashion.html",
      "classification": "action",
      "filename": "bffs-retro-time-travel-fashion"
    },
    {
      "name": "BFFs Summer Aesthetic",
      "file": "games/action/bffs-summer-aesthetic.html",
      "classification": "action",
      "filename": "bffs-summer-aesthetic"
    },
    {
      "name": "Happy Crayons",
      "file": "games/action/happy-crayons.html",
      "classification": "action",
      "filename": "happy-crayons"
    },
    {
      "name": "Witch Beauty Salon",
      "file": "games/action/witch-beauty-salon.html",
      "classification": "action",
      "filename": "witch-beauty-salon"
    },
    {
      "name": "Cat Doctor",
      "file": "games/action/cat-doctor.html",
      "classification": "action",
      "filename": "cat-doctor"
    },
    {
      "name": "Foot Doctor",
      "file": "games/action/foot-doctor.html",
      "classification": "action",
      "filename": "foot-doctor"
    },
    {
      "name": "Weird Dance on Wednesday",
      "file": "games/action/weird-dance-on-wednesday.html",
      "classification": "action",
      "filename": "weird-dance-on-wednesday"
    },
    {
      "name": "Ellie Thanksgiving Day",
      "file": "games/action/ellie-thanksgiving-day.html",
      "classification": "action",
      "filename": "ellie-thanksgiving-day"
    },
    {
      "name": "Trendy Plaid Outfits",
      "file": "games/action/trendy-plaid-outfits.html",
      "classification": "action",
      "filename": "trendy-plaid-outfits"
    },
    {
      "name": "Unicorn Dress Up",
      "file": "games/action/unicorn-dress-up.html",
      "classification": "action",
      "filename": "unicorn-dress-up"
    },
    {
      "name": "Gold Miner",
      "file": "games/action/gold-miner.html",
      "classification": "action",
      "filename": "gold-miner"
    },
    {
      "name": "Dreamlike Room",
      "file": "games/action/dreamlike-room.html",
      "classification": "action",
      "filename": "dreamlike-room"
    },
    {
      "name": "Iconic Celebrity Look",
      "file": "games/action/iconic-celebrity-look.html",
      "classification": "action",
      "filename": "iconic-celebrity-look"
    },
    {
      "name": "Get Ready Summer Picnic",
      "file": "games/action/get-ready-summer-picnic.html",
      "classification": "action",
      "filename": "get-ready-summer-picnic"
    },
    {
      "name": "Dinosaur Game",
      "file": "games/action/dinosaur-game.html",
      "classification": "action",
      "filename": "dinosaur-game"
    },
    {
      "name": "Winterella",
      "file": "games/action/winterella.html",
      "classification": "action",
      "filename": "winterella"
    },
    {
      "name": "Princesses Prom Night",
      "file": "games/action/princesses-prom-night.html",
      "classification": "action",
      "filename": "princesses-prom-night"
    },
    {
      "name": "Car Wash",
      "file": "games/action/car-wash.html",
      "classification": "action",
      "filename": "car-wash"
    },
    {
      "name": "Princess Beauty Salon",
      "file": "games/action/princess-beauty-salon.html",
      "classification": "action",
      "filename": "princess-beauty-salon"
    },
    {
      "name": "Ice Slushy Maker",
      "file": "games/action/ice-slushy-maker.html",
      "classification": "action",
      "filename": "ice-slushy-maker"
    },
    {
      "name": "Pets Beauty Salon",
      "file": "games/action/pets-beauty-salon.html",
      "classification": "action",
      "filename": "pets-beauty-salon"
    },
    {
      "name": "Rooftop Snipers",
      "file": "games/action/rooftop-snipers.html",
      "classification": "action",
      "filename": "rooftop-snipers"
    },
    {
      "name": "GunSpin",
      "file": "games/action/gunspin.html",
      "classification": "action",
      "filename": "gunspin"
    },
    {
      "name": "Rooftop Duel",
      "file": "games/action/rooftop-duel.html",
      "classification": "action",
      "filename": "rooftop-duel"
    },
    {
      "name": "Deer Hunter",
      "file": "games/action/deer-hunter.html",
      "classification": "action",
      "filename": "deer-hunter"
    },
    {
      "name": "Urban Sniper",
      "file": "games/action/urban-sniper.html",
      "classification": "action",
      "filename": "urban-sniper"
    },
    {
      "name": "Battle Royale Simulator",
      "file": "games/action/battle-royale-simulator.html",
      "classification": "action",
      "filename": "battle-royale-simulator"
    },
    {
      "name": "Awesome Pirates",
      "file": "games/action/awesome-pirates.html",
      "classification": "action",
      "filename": "awesome-pirates"
    },
    {
      "name": "Sniper Elite",
      "file": "games/action/sniper-elite.html",
      "classification": "action",
      "filename": "sniper-elite"
    },
    {
      "name": "Zombie Sniper",
      "file": "games/action/zombie-sniper.html",
      "classification": "action",
      "filename": "zombie-sniper"
    },
    {
      "name": "Backrooms Shooter",
      "file": "games/action/backrooms-shooter.html",
      "classification": "action",
      "filename": "backrooms-shooter"
    },
    {
      "name": "Skibidi Strike",
      "file": "games/action/skibidi-strike.html",
      "classification": "action",
      "filename": "skibidi-strike"
    },
    {
      "name": "Funny Shooter",
      "file": "games/action/funny-shooter.html",
      "classification": "action",
      "filename": "funny-shooter"
    },
    {
      "name": "Rainbow Survival",
      "file": "games/action/rainbow-survival.html",
      "classification": "action",
      "filename": "rainbow-survival"
    },
    {
      "name": "Stickman War",
      "file": "games/action/stickman-war.html",
      "classification": "action",
      "filename": "stickman-war"
    },
    {
      "name": "Sniper Reloaded",
      "file": "games/action/sniper-reloaded.html",
      "classification": "action",
      "filename": "sniper-reloaded"
    },
    {
      "name": "Galactic Sniper",
      "file": "games/action/galactic-sniper.html",
      "classification": "action",
      "filename": "galactic-sniper"
    },
    {
      "name": "Squad Shooter",
      "file": "games/action/squad-shooter.html",
      "classification": "action",
      "filename": "squad-shooter"
    },
    {
      "name": "Zombie War Defense",
      "file": "games/action/zombie-war-defense.html",
      "classification": "action",
      "filename": "zombie-war-defense"
    },
    {
      "name": "Archery Master",
      "file": "games/action/archery-master.html",
      "classification": "action",
      "filename": "archery-master"
    },
    {
      "name": "Pixel Battle Royale",
      "file": "games/action/pixel-battle-royale.html",
      "classification": "action",
      "filename": "pixel-battle-royale"
    },
    {
      "name": "Tank Driver Simulator",
      "file": "games/action/tank-driver-simulator.html",
      "classification": "action",
      "filename": "tank-driver-simulator"
    },
    {
      "name": "Age of War",
      "file": "games/action/age-of-war.html",
      "classification": "action",
      "filename": "age-of-war"
    },
    {
      "name": "Agent Walker vs Skibidi Toilets",
      "file": "games/action/agent-walker-vs-skibidi-toilets.html",
      "classification": "action",
      "filename": "agent-walker-vs-skibidi-toilets"
    },
    {
      "name": "Counter Craft",
      "file": "games/action/counter-craft.html",
      "classification": "action",
      "filename": "counter-craft"
    },
    {
      "name": "Car Transform Racing",
      "file": "games/action/car-transform-racing.html",
      "classification": "action",
      "filename": "car-transform-racing"
    },
    {
      "name": "Speed Drift Racing",
      "file": "games/action/speed-drift-racing.html",
      "classification": "action",
      "filename": "speed-drift-racing"
    },
    {
      "name": "Monster Truck Stunts",
      "file": "games/action/monster-truck-stunts.html",
      "classification": "action",
      "filename": "monster-truck-stunts"
    },
    {
      "name": "Duck Life 4",
      "file": "games/action/duck-life-4.html",
      "classification": "action",
      "filename": "duck-life-4"
    },
    {
      "name": "Marble Run: Ultimate Race",
      "file": "games/action/marble-run-ultimate-race.html",
      "classification": "action",
      "filename": "marble-run-ultimate-race"
    },
    {
      "name": "Stack Fire Ball",
      "file": "games/action/stack-fire-ball.html",
      "classification": "action",
      "filename": "stack-fire-ball"
    },
    {
      "name": "Geometry Arrow 2",
      "file": "games/action/geometry-arrow-2.html",
      "classification": "action",
      "filename": "geometry-arrow-2"
    },
    {
      "name": "Run 3",
      "file": "games/action/run-3.html",
      "classification": "action",
      "filename": "run-3"
    },
    {
      "name": "Geometry Dash",
      "file": "games/action/geometry-dash.html",
      "classification": "action",
      "filename": "geometry-dash"
    },
    {
      "name": "Idle Breakout",
      "file": "games/action/idle-breakout.html",
      "classification": "action",
      "filename": "idle-breakout"
    },
    {
      "name": "Basket Random",
      "file": "games/action/basket-random.html",
      "classification": "action",
      "filename": "basket-random"
    },
    {
      "name": "Obby Bike Trials",
      "file": "games/action/obby-bike-trials.html",
      "classification": "action",
      "filename": "obby-bike-trials"
    },
    {
      "name": "3D Dash",
      "file": "games/action/3d-dash.html",
      "classification": "action",
      "filename": "3d-dash"
    },
    {
      "name": "Slope Run",
      "file": "games/action/slope-run.html",
      "classification": "action",
      "filename": "slope-run"
    },
    {
      "name": "Papa's Donuteria",
      "file": "games/action/papas-donuteria.html",
      "classification": "action",
      "filename": "papas-donuteria"
    },
    {
      "name": "A Small World Cup",
      "file": "games/action/a-small-world-cup.html",
      "classification": "action",
      "filename": "a-small-world-cup"
    },
    {
      "name": "Papa's Taco Mia",
      "file": "games/action/papas-taco-mia.html",
      "classification": "action",
      "filename": "papas-taco-mia"
    },
    {
      "name": "Monster Dash",
      "file": "games/action/monster-dash.html",
      "classification": "action",
      "filename": "monster-dash"
    },
    {
      "name": "Pacman 30th Anniversary",
      "file": "games/action/pacman-30th-anniversary.html",
      "classification": "action",
      "filename": "pacman-30th-anniversary"
    },
    {
      "name": "Obby Tower Parkour Climb",
      "file": "games/action/obby-tower-parkour-climb.html",
      "classification": "action",
      "filename": "obby-tower-parkour-climb"
    },
    {
      "name": "OvO",
      "file": "games/action/ovo.html",
      "classification": "action",
      "filename": "ovo"
    },
    {
      "name": "Soccer Random",
      "file": "games/action/soccer-random.html",
      "classification": "action",
      "filename": "soccer-random"
    },
    {
      "name": "Ragdoll Football 2 Players",
      "file": "games/action/ragdoll-football-2-players.html",
      "classification": "action",
      "filename": "ragdoll-football-2-players"
    },
    {
      "name": "Asian Cup Soccer",
      "file": "games/action/asian-cup-soccer.html",
      "classification": "action",
      "filename": "asian-cup-soccer"
    },
    {
      "name": "Friday Night Funkin",
      "file": "games/action/friday-night-funkin.html",
      "classification": "action",
      "filename": "friday-night-funkin"
    },
    {
      "name": "Flappy Bird",
      "file": "games/action/flappy-bird.html",
      "classification": "action",
      "filename": "flappy-bird"
    },
    {
      "name": "Hoop World 3D",
      "file": "games/action/hoop-world-3d.html",
      "classification": "action",
      "filename": "hoop-world-3d"
    },
    {
      "name": "Boxing Random",
      "file": "games/action/boxing-random.html",
      "classification": "action",
      "filename": "boxing-random"
    },
    {
      "name": "Tennis Masters",
      "file": "games/action/tennis-masters.html",
      "classification": "action",
      "filename": "tennis-masters"
    },
    {
      "name": "FNF Garcello",
      "file": "games/action/fnf-garcello.html",
      "classification": "action",
      "filename": "fnf-garcello"
    },
    {
      "name": "Soccer Random Pro",
      "file": "games/action/soccer-random-pro.html",
      "classification": "action",
      "filename": "soccer-random-pro"
    },
    {
      "name": "Soccer Masters",
      "file": "games/action/soccer-masters.html",
      "classification": "action",
      "filename": "soccer-masters"
    },
    {
      "name": "Boxing Stars",
      "file": "games/action/boxing-stars.html",
      "classification": "action",
      "filename": "boxing-stars"
    },
    {
      "name": "Bus Subway Runner",
      "file": "games/action/bus-subway-runner.html",
      "classification": "action",
      "filename": "bus-subway-runner"
    },
    {
      "name": "Geometry Dash FreezeNova",
      "file": "games/action/geometry-dash-freezenova.html",
      "classification": "action",
      "filename": "geometry-dash-freezenova"
    },
    {
      "name": "Stickman Ragdoll",
      "file": "games/action/stickman-ragdoll.html",
      "classification": "action",
      "filename": "stickman-ragdoll"
    },
    {
      "name": "War of Tanks Paper Note",
      "file": "games/action/war-of-tanks-paper-note.html",
      "classification": "action",
      "filename": "war-of-tanks-paper-note"
    },
    {
      "name": "Run 3D",
      "file": "games/action/run-3d.html",
      "classification": "action",
      "filename": "run-3d"
    },
    {
      "name": "Basketball Slam Dunk",
      "file": "games/action/basketball-slam-dunk.html",
      "classification": "action",
      "filename": "basketball-slam-dunk"
    },
    {
      "name": "World's Hardest Game",
      "file": "games/action/worlds-hardest-game.html",
      "classification": "action",
      "filename": "worlds-hardest-game"
    },
    {
      "name": "Sword Play Ninja Slice Runner",
      "file": "games/action/sword-play-ninja-slice-runner.html",
      "classification": "action",
      "filename": "sword-play-ninja-slice-runner"
    },
    {
      "name": "Tunnel Road",
      "file": "games/action/tunnel-road.html",
      "classification": "action",
      "filename": "tunnel-road"
    },
    {
      "name": "SpartaHoppers",
      "file": "games/action/spartahoppers.html",
      "classification": "action",
      "filename": "spartahoppers"
    },
    {
      "name": "Backflip Dive 3D",
      "file": "games/action/backflip-dive-3d.html",
      "classification": "action",
      "filename": "backflip-dive-3d"
    },
    {
      "name": "Life Simulator",
      "file": "games/action/life-simulator.html",
      "classification": "action",
      "filename": "life-simulator"
    },
    {
      "name": "Real Flight Simulator",
      "file": "games/action/real-flight-simulator.html",
      "classification": "action",
      "filename": "real-flight-simulator"
    },
    {
      "name": "Checkout Frenzy",
      "file": "games/action/checkout-frenzy.html",
      "classification": "action",
      "filename": "checkout-frenzy"
    },
    {
      "name": "Battle Simulator: Sandbox",
      "file": "games/action/battle-simulator-sandbox.html",
      "classification": "action",
      "filename": "battle-simulator-sandbox"
    },
    {
      "name": "Crazy Plane Landing",
      "file": "games/action/crazy-plane-landing.html",
      "classification": "action",
      "filename": "crazy-plane-landing"
    },
    {
      "name": "Subway Idle 3D",
      "file": "games/action/subway-idle-3d.html",
      "classification": "action",
      "filename": "subway-idle-3d"
    },
    {
      "name": "Fast Food Rush",
      "file": "games/action/fast-food-rush.html",
      "classification": "action",
      "filename": "fast-food-rush"
    },
    {
      "name": "Stickman Destruction",
      "file": "games/action/stickman-destruction.html",
      "classification": "action",
      "filename": "stickman-destruction"
    },
    {
      "name": "Supermarket Simulator",
      "file": "games/action/supermarket-simulator.html",
      "classification": "action",
      "filename": "supermarket-simulator"
    },
    {
      "name": "Idle Mining Empire",
      "file": "games/action/idle-mining-empire.html",
      "classification": "action",
      "filename": "idle-mining-empire"
    },
    {
      "name": "Logistics Inc",
      "file": "games/action/logistics-inc.html",
      "classification": "action",
      "filename": "logistics-inc"
    },
    {
      "name": "Idle Vlogger",
      "file": "games/action/idle-vlogger.html",
      "classification": "action",
      "filename": "idle-vlogger"
    },
    {
      "name": "Football Soccer World Cup",
      "file": "games/action/football-soccer-world-cup.html",
      "classification": "action",
      "filename": "football-soccer-world-cup"
    },
    {
      "name": "City Bus Driver",
      "file": "games/action/city-bus-driver.html",
      "classification": "action",
      "filename": "city-bus-driver"
    },
    {
      "name": "Train Simulator",
      "file": "games/action/train-simulator.html",
      "classification": "action",
      "filename": "train-simulator"
    },
    {
      "name": "God Simulator",
      "file": "games/action/god-simulator.html",
      "classification": "action",
      "filename": "god-simulator"
    }
  ],
  "adventure": [
    {
      "name": "Drac & Franc",
      "file": "games/adventure/drac-franc.html",
      "classification": "adventure",
      "filename": "drac-franc"
    },
    {
      "name": "Minecraft Classic",
      "file": "games/adventure/minecraft-classic.html",
      "classification": "adventure",
      "filename": "minecraft-classic"
    },
    {
      "name": "Hole Digger",
      "file": "games/adventure/hole-digger.html",
      "classification": "adventure",
      "filename": "hole-digger"
    },
    {
      "name": "Fireboy and Watergirl",
      "file": "games/adventure/fireboy-and-watergirl.html",
      "classification": "adventure",
      "filename": "fireboy-and-watergirl"
    },
    {
      "name": "Cube Worlds",
      "file": "games/adventure/cube-worlds.html",
      "classification": "adventure",
      "filename": "cube-worlds"
    },
    {
      "name": "Paper Minecraft",
      "file": "games/adventure/paper-minecraft.html",
      "classification": "adventure",
      "filename": "paper-minecraft"
    },
    {
      "name": "Cat Simulator",
      "file": "games/adventure/cat-simulator.html",
      "classification": "adventure",
      "filename": "cat-simulator"
    },
    {
      "name": "Mergest Kingdom",
      "file": "games/adventure/mergest-kingdom.html",
      "classification": "adventure",
      "filename": "mergest-kingdom"
    },
    {
      "name": "Craftmine",
      "file": "games/adventure/craftmine.html",
      "classification": "adventure",
      "filename": "craftmine"
    },
    {
      "name": "We Become What We Behold",
      "file": "games/adventure/we-become-what-we-behold.html",
      "classification": "adventure",
      "filename": "we-become-what-we-behold"
    },
    {
      "name": "Parkour Block 3D",
      "file": "games/adventure/parkour-block-3d.html",
      "classification": "adventure",
      "filename": "parkour-block-3d"
    },
    {
      "name": "Mine Clone",
      "file": "games/adventure/mine-clone.html",
      "classification": "adventure",
      "filename": "mine-clone"
    },
    {
      "name": "Fortnite Z",
      "file": "games/adventure/fortnite-z.html",
      "classification": "adventure",
      "filename": "fortnite-z"
    },
    {
      "name": "Fancy Pants 3",
      "file": "games/adventure/fancy-pants-3.html",
      "classification": "adventure",
      "filename": "fancy-pants-3"
    },
    {
      "name": "Only Up or Lava",
      "file": "games/adventure/only-up-or-lava.html",
      "classification": "adventure",
      "filename": "only-up-or-lava"
    },
    {
      "name": "Survival Craft",
      "file": "games/adventure/survival-craft.html",
      "classification": "adventure",
      "filename": "survival-craft"
    },
    {
      "name": "Survival Island",
      "file": "games/adventure/survival-island.html",
      "classification": "adventure",
      "filename": "survival-island"
    },
    {
      "name": "Hero Dragon Power",
      "file": "games/adventure/hero-dragon-power.html",
      "classification": "adventure",
      "filename": "hero-dragon-power"
    },
    {
      "name": "Dragon City",
      "file": "games/adventure/dragon-city.html",
      "classification": "adventure",
      "filename": "dragon-city"
    },
    {
      "name": "Vex 7",
      "file": "games/adventure/vex-7.html",
      "classification": "adventure",
      "filename": "vex-7"
    },
    {
      "name": "Epic Mine",
      "file": "games/adventure/epic-mine.html",
      "classification": "adventure",
      "filename": "epic-mine"
    },
    {
      "name": "Blocky Parkour Ninja",
      "file": "games/adventure/blocky-parkour-ninja.html",
      "classification": "adventure",
      "filename": "blocky-parkour-ninja"
    },
    {
      "name": "Poptropica",
      "file": "games/adventure/poptropica.html",
      "classification": "adventure",
      "filename": "poptropica"
    },
    {
      "name": "Help the Hero",
      "file": "games/adventure/help-the-hero.html",
      "classification": "adventure",
      "filename": "help-the-hero"
    },
    {
      "name": "Fire and Water",
      "file": "games/adventure/fire-and-water.html",
      "classification": "adventure",
      "filename": "fire-and-water"
    },
    {
      "name": "Top Burger Cooking",
      "file": "games/adventure/top-burger-cooking.html",
      "classification": "adventure",
      "filename": "top-burger-cooking"
    },
    {
      "name": "The Farmer Craft",
      "file": "games/adventure/the-farmer-craft.html",
      "classification": "adventure",
      "filename": "the-farmer-craft"
    },
    {
      "name": "Horse Family Animal Simulator",
      "file": "games/adventure/horse-family-animal-simulator.html",
      "classification": "adventure",
      "filename": "horse-family-animal-simulator"
    },
    {
      "name": "Agent Smith",
      "file": "games/adventure/agent-smith.html",
      "classification": "adventure",
      "filename": "agent-smith"
    },
    {
      "name": "Voxel World",
      "file": "games/adventure/voxel-world.html",
      "classification": "adventure",
      "filename": "voxel-world"
    },
    {
      "name": "Dynamons World",
      "file": "games/adventure/dynamons-world.html",
      "classification": "adventure",
      "filename": "dynamons-world"
    },
    {
      "name": "Home Makeover 2: Hidden Object",
      "file": "games/adventure/home-makeover-2-hidden-object.html",
      "classification": "adventure",
      "filename": "home-makeover-2-hidden-object"
    },
    {
      "name": "Papa Louie",
      "file": "games/adventure/papa-louie.html",
      "classification": "adventure",
      "filename": "papa-louie"
    },
    {
      "name": "Marco",
      "file": "games/adventure/marco.html",
      "classification": "adventure",
      "filename": "marco"
    },
    {
      "name": "Fantasy Tower Defense",
      "file": "games/adventure/fantasy-tower-defense.html",
      "classification": "adventure",
      "filename": "fantasy-tower-defense"
    },
    {
      "name": "Duck Life Space",
      "file": "games/adventure/duck-life-space.html",
      "classification": "adventure",
      "filename": "duck-life-space"
    },
    {
      "name": "Conquer Kingdoms",
      "file": "games/adventure/conquer-kingdoms.html",
      "classification": "adventure",
      "filename": "conquer-kingdoms"
    },
    {
      "name": "Fancy Pants",
      "file": "games/adventure/fancy-pants.html",
      "classification": "adventure",
      "filename": "fancy-pants"
    },
    {
      "name": "Jacks Village",
      "file": "games/adventure/jacks-village.html",
      "classification": "adventure",
      "filename": "jacks-village"
    },
    {
      "name": "Valkyrie RPG",
      "file": "games/adventure/valkyrie-rpg.html",
      "classification": "adventure",
      "filename": "valkyrie-rpg"
    },
    {
      "name": "Duck Life Adventure",
      "file": "games/adventure/duck-life-adventure.html",
      "classification": "adventure",
      "filename": "duck-life-adventure"
    },
    {
      "name": "Math vs Bat",
      "file": "games/adventure/math-vs-bat.html",
      "classification": "adventure",
      "filename": "math-vs-bat"
    },
    {
      "name": "Pirate Adventure",
      "file": "games/adventure/pirate-adventure.html",
      "classification": "adventure",
      "filename": "pirate-adventure"
    },
    {
      "name": "Cake Shop",
      "file": "games/adventure/cake-shop.html",
      "classification": "adventure",
      "filename": "cake-shop"
    },
    {
      "name": "Fancy Pants 2",
      "file": "games/adventure/fancy-pants-2.html",
      "classification": "adventure",
      "filename": "fancy-pants-2"
    },
    {
      "name": "Soul Essence Adventure",
      "file": "games/adventure/soul-essence-adventure.html",
      "classification": "adventure",
      "filename": "soul-essence-adventure"
    },
    {
      "name": "Treasure Hunter",
      "file": "games/adventure/treasure-hunter.html",
      "classification": "adventure",
      "filename": "treasure-hunter"
    },
    {
      "name": "Edelweiss",
      "file": "games/adventure/edelweiss.html",
      "classification": "adventure",
      "filename": "edelweiss"
    }
  ],
  "puzzle": [
    {
      "name": "BlockBuster Puzzle",
      "file": "games/puzzle/blockbuster-puzzle.html",
      "classification": "puzzle",
      "filename": "blockbuster-puzzle"
    },
    {
      "name": "Sprunky Incredibox Mods",
      "file": "games/puzzle/sprunky-incredibox-mods.html",
      "classification": "puzzle",
      "filename": "sprunky-incredibox-mods"
    },
    {
      "name": "Merge Cakes",
      "file": "games/puzzle/merge-cakes.html",
      "classification": "puzzle",
      "filename": "merge-cakes"
    },
    {
      "name": "Watermelon Game",
      "file": "games/puzzle/watermelon-game.html",
      "classification": "puzzle",
      "filename": "watermelon-game"
    },
    {
      "name": "Home Design",
      "file": "games/puzzle/home-design.html",
      "classification": "puzzle",
      "filename": "home-design"
    },
    {
      "name": "Cake Match Puzzle",
      "file": "games/puzzle/cake-match-puzzle.html",
      "classification": "puzzle",
      "filename": "cake-match-puzzle"
    },
    {
      "name": "Wordle",
      "file": "games/puzzle/wordle.html",
      "classification": "puzzle",
      "filename": "wordle"
    },
    {
      "name": "Bookworm",
      "file": "games/puzzle/bookworm.html",
      "classification": "puzzle",
      "filename": "bookworm"
    },
    {
      "name": "Nova Craft",
      "file": "games/puzzle/nova-craft.html",
      "classification": "puzzle",
      "filename": "nova-craft"
    },
    {
      "name": "Words from Words",
      "file": "games/puzzle/words-from-words.html",
      "classification": "puzzle",
      "filename": "words-from-words"
    },
    {
      "name": "Mathematical Crossword",
      "file": "games/puzzle/mathematical-crossword.html",
      "classification": "puzzle",
      "filename": "mathematical-crossword"
    },
    {
      "name": "Tile Match",
      "file": "games/puzzle/tile-match.html",
      "classification": "puzzle",
      "filename": "tile-match"
    },
    {
      "name": "Mahjong",
      "file": "games/puzzle/mahjong.html",
      "classification": "puzzle",
      "filename": "mahjong"
    },
    {
      "name": "Wood Block Jam",
      "file": "games/puzzle/wood-block-jam.html",
      "classification": "puzzle",
      "filename": "wood-block-jam"
    },
    {
      "name": "2048",
      "file": "games/puzzle/2048.html",
      "classification": "puzzle",
      "filename": "2048"
    },
    {
      "name": "Find It",
      "file": "games/puzzle/find-it.html",
      "classification": "puzzle",
      "filename": "find-it"
    },
    {
      "name": "Sudoku",
      "file": "games/puzzle/sudoku.html",
      "classification": "puzzle",
      "filename": "sudoku"
    },
    {
      "name": "Vega Mix: Sea Adventures",
      "file": "games/puzzle/vega-mix-sea-adventures.html",
      "classification": "puzzle",
      "filename": "vega-mix-sea-adventures"
    },
    {
      "name": "The House",
      "file": "games/puzzle/the-house.html",
      "classification": "puzzle",
      "filename": "the-house"
    },
    {
      "name": "Stick Hero Mighty Tower Wars",
      "file": "games/puzzle/stick-hero-mighty-tower-wars.html",
      "classification": "puzzle",
      "filename": "stick-hero-mighty-tower-wars"
    },
    {
      "name": "Tiny Crash Fighters",
      "file": "games/puzzle/tiny-crash-fighters.html",
      "classification": "puzzle",
      "filename": "tiny-crash-fighters"
    },
    {
      "name": "House Painter",
      "file": "games/puzzle/house-painter.html",
      "classification": "puzzle",
      "filename": "house-painter"
    },
    {
      "name": "Hidden Objects: Brain Teaser",
      "file": "games/puzzle/hidden-objects-brain-teaser.html",
      "classification": "puzzle",
      "filename": "hidden-objects-brain-teaser"
    },
    {
      "name": "Sort Resort",
      "file": "games/puzzle/sort-resort.html",
      "classification": "puzzle",
      "filename": "sort-resort"
    },
    {
      "name": "Bubble Up Endless",
      "file": "games/puzzle/bubble-up-endless.html",
      "classification": "puzzle",
      "filename": "bubble-up-endless"
    },
    {
      "name": "Watermelon Suika",
      "file": "games/puzzle/watermelon-suika.html",
      "classification": "puzzle",
      "filename": "watermelon-suika"
    },
    {
      "name": "Cool Math",
      "file": "games/puzzle/cool-math.html",
      "classification": "puzzle",
      "filename": "cool-math"
    },
    {
      "name": "Draw Here",
      "file": "games/puzzle/draw-here.html",
      "classification": "puzzle",
      "filename": "draw-here"
    },
    {
      "name": "Unblock It 3D",
      "file": "games/puzzle/unblock-it-3d.html",
      "classification": "puzzle",
      "filename": "unblock-it-3d"
    },
    {
      "name": "Mini Crossword",
      "file": "games/puzzle/mini-crossword.html",
      "classification": "puzzle",
      "filename": "mini-crossword"
    },
    {
      "name": "The Smurfs: Village Cleaning",
      "file": "games/puzzle/the-smurfs-village-cleaning.html",
      "classification": "puzzle",
      "filename": "the-smurfs-village-cleaning"
    },
    {
      "name": "Solitaire Adventure",
      "file": "games/puzzle/solitaire-adventure.html",
      "classification": "puzzle",
      "filename": "solitaire-adventure"
    },
    {
      "name": "Bullet Master",
      "file": "games/puzzle/bullet-master.html",
      "classification": "puzzle",
      "filename": "bullet-master"
    },
    {
      "name": "Wordmeister",
      "file": "games/puzzle/wordmeister.html",
      "classification": "puzzle",
      "filename": "wordmeister"
    },
    {
      "name": "Grandmaster Chess",
      "file": "games/puzzle/grandmaster-chess.html",
      "classification": "puzzle",
      "filename": "grandmaster-chess"
    },
    {
      "name": "Quordle Today",
      "file": "games/puzzle/quordle-today.html",
      "classification": "puzzle",
      "filename": "quordle-today"
    },
    {
      "name": "Draw the Truck Bridge",
      "file": "games/puzzle/draw-the-truck-bridge.html",
      "classification": "puzzle",
      "filename": "draw-the-truck-bridge"
    },
    {
      "name": "Christmas Mahjong",
      "file": "games/puzzle/christmas-mahjong.html",
      "classification": "puzzle",
      "filename": "christmas-mahjong"
    },
    {
      "name": "Hexotopia",
      "file": "games/puzzle/hexotopia.html",
      "classification": "puzzle",
      "filename": "hexotopia"
    },
    {
      "name": "Draw the Bird Path",
      "file": "games/puzzle/draw-the-bird-path.html",
      "classification": "puzzle",
      "filename": "draw-the-bird-path"
    },
    {
      "name": "Chess Fill",
      "file": "games/puzzle/chess-fill.html",
      "classification": "puzzle",
      "filename": "chess-fill"
    },
    {
      "name": "Ancient 2048",
      "file": "games/puzzle/ancient-2048.html",
      "classification": "puzzle",
      "filename": "ancient-2048"
    },
    {
      "name": "Pirate Shootout",
      "file": "games/puzzle/pirate-shootout.html",
      "classification": "puzzle",
      "filename": "pirate-shootout"
    },
    {
      "name": "Math Trivia",
      "file": "games/puzzle/math-trivia.html",
      "classification": "puzzle",
      "filename": "math-trivia"
    },
    {
      "name": "Classic Minesweeper",
      "file": "games/puzzle/classic-minesweeper.html",
      "classification": "puzzle",
      "filename": "classic-minesweeper"
    },
    {
      "name": "Hero Tower",
      "file": "games/puzzle/hero-tower.html",
      "classification": "puzzle",
      "filename": "hero-tower"
    },
    {
      "name": "Marble Zumba Stack",
      "file": "games/puzzle/marble-zumba-stack.html",
      "classification": "puzzle",
      "filename": "marble-zumba-stack"
    },
    {
      "name": "Sudoku Village",
      "file": "games/puzzle/sudoku-village.html",
      "classification": "puzzle",
      "filename": "sudoku-village"
    },
    {
      "name": "Hexologic",
      "file": "games/puzzle/hexologic.html",
      "classification": "puzzle",
      "filename": "hexologic"
    },
    {
      "name": "Blocky Blast",
      "file": "games/puzzle/blocky-blast.html",
      "classification": "puzzle",
      "filename": "blocky-blast"
    },
    {
      "name": "Candy Bubble",
      "file": "games/puzzle/candy-bubble.html",
      "classification": "puzzle",
      "filename": "candy-bubble"
    },
    {
      "name": "Text Talk",
      "file": "games/puzzle/text-talk.html",
      "classification": "puzzle",
      "filename": "text-talk"
    },
    {
      "name": "Mr Dracula",
      "file": "games/puzzle/mr-dracula.html",
      "classification": "puzzle",
      "filename": "mr-dracula"
    },
    {
      "name": "Sweet Sugar Match",
      "file": "games/puzzle/sweet-sugar-match.html",
      "classification": "puzzle",
      "filename": "sweet-sugar-match"
    }
  ],
  "sports": [
    {
      "name": "Draw the Car Path",
      "file": "games/sports/draw-the-car-path.html",
      "classification": "sports",
      "filename": "draw-the-car-path"
    },
    {
      "name": "Drift King",
      "file": "games/sports/drift-king.html",
      "classification": "sports",
      "filename": "drift-king"
    },
    {
      "name": "Police Simulator",
      "file": "games/sports/police-simulator.html",
      "classification": "sports",
      "filename": "police-simulator"
    },
    {
      "name": "Drift Hunters 2",
      "file": "games/sports/drift-hunters-2.html",
      "classification": "sports",
      "filename": "drift-hunters-2"
    },
    {
      "name": "Traffic Jam 3D",
      "file": "games/sports/traffic-jam-3d.html",
      "classification": "sports",
      "filename": "traffic-jam-3d"
    },
    {
      "name": "Highway Traffic",
      "file": "games/sports/highway-traffic.html",
      "classification": "sports",
      "filename": "highway-traffic"
    },
    {
      "name": "Street Traffic Racer",
      "file": "games/sports/street-traffic-racer.html",
      "classification": "sports",
      "filename": "street-traffic-racer"
    },
    {
      "name": "Drift Boss",
      "file": "games/sports/drift-boss.html",
      "classification": "sports",
      "filename": "drift-boss"
    },
    {
      "name": "Tow N Go",
      "file": "games/sports/tow-n-go.html",
      "classification": "sports",
      "filename": "tow-n-go"
    },
    {
      "name": "Drift Hunters Pro",
      "file": "games/sports/drift-hunters-pro.html",
      "classification": "sports",
      "filename": "drift-hunters-pro"
    },
    {
      "name": "Drift Hunters",
      "file": "games/sports/drift-hunters.html",
      "classification": "sports",
      "filename": "drift-hunters"
    },
    {
      "name": "Turbo Race 3D",
      "file": "games/sports/turbo-race-3d.html",
      "classification": "sports",
      "filename": "turbo-race-3d"
    },
    {
      "name": "Mega Lamba Ramp",
      "file": "games/sports/mega-lamba-ramp.html",
      "classification": "sports",
      "filename": "mega-lamba-ramp"
    },
    {
      "name": "Edys Car Simulator",
      "file": "games/sports/edys-car-simulator.html",
      "classification": "sports",
      "filename": "edys-car-simulator"
    },
    {
      "name": "Escape Car",
      "file": "games/sports/escape-car.html",
      "classification": "sports",
      "filename": "escape-car"
    },
    {
      "name": "Vehicles Simulator",
      "file": "games/sports/vehicles-simulator.html",
      "classification": "sports",
      "filename": "vehicles-simulator"
    },
    {
      "name": "Drift Rider",
      "file": "games/sports/drift-rider.html",
      "classification": "sports",
      "filename": "drift-rider"
    },
    {
      "name": "Madalin Stunt Cars Pro",
      "file": "games/sports/madalin-stunt-cars-pro.html",
      "classification": "sports",
      "filename": "madalin-stunt-cars-pro"
    },
    {
      "name": "Police Chase Drifter",
      "file": "games/sports/police-chase-drifter.html",
      "classification": "sports",
      "filename": "police-chase-drifter"
    },
    {
      "name": "Super Car Driving",
      "file": "games/sports/super-car-driving.html",
      "classification": "sports",
      "filename": "super-car-driving"
    },
    {
      "name": "Car Parking City Duel",
      "file": "games/sports/car-parking-city-duel.html",
      "classification": "sports",
      "filename": "car-parking-city-duel"
    },
    {
      "name": "Burnout City",
      "file": "games/sports/burnout-city.html",
      "classification": "sports",
      "filename": "burnout-city"
    },
    {
      "name": "Highway Racer Pro",
      "file": "games/sports/highway-racer-pro.html",
      "classification": "sports",
      "filename": "highway-racer-pro"
    },
    {
      "name": "Carnage Battle Arena",
      "file": "games/sports/carnage-battle-arena.html",
      "classification": "sports",
      "filename": "carnage-battle-arena"
    },
    {
      "name": "Ultimate Flying Car",
      "file": "games/sports/ultimate-flying-car.html",
      "classification": "sports",
      "filename": "ultimate-flying-car"
    },
    {
      "name": "American Truck Car Driving",
      "file": "games/sports/american-truck-car-driving.html",
      "classification": "sports",
      "filename": "american-truck-car-driving"
    },
    {
      "name": "Highway Cars",
      "file": "games/sports/highway-cars.html",
      "classification": "sports",
      "filename": "highway-cars"
    },
    {
      "name": "Crazy Drifter",
      "file": "games/sports/crazy-drifter.html",
      "classification": "sports",
      "filename": "crazy-drifter"
    },
    {
      "name": "Ultimate Flying Car 2",
      "file": "games/sports/ultimate-flying-car-2.html",
      "classification": "sports",
      "filename": "ultimate-flying-car-2"
    },
    {
      "name": "Highway Road Racing",
      "file": "games/sports/highway-road-racing.html",
      "classification": "sports",
      "filename": "highway-road-racing"
    },
    {
      "name": "Drift City",
      "file": "games/sports/drift-city.html",
      "classification": "sports",
      "filename": "drift-city"
    },
    {
      "name": "Hill Climb Racing Scratch",
      "file": "games/sports/hill-climb-racing-scratch.html",
      "classification": "sports",
      "filename": "hill-climb-racing-scratch"
    },
    {
      "name": "Racing Horizon",
      "file": "games/sports/racing-horizon.html",
      "classification": "sports",
      "filename": "racing-horizon"
    },
    {
      "name": "Slow Roads",
      "file": "games/sports/slow-roads.html",
      "classification": "sports",
      "filename": "slow-roads"
    },
    {
      "name": "F1 Drift Racer",
      "file": "games/sports/f1-drift-racer.html",
      "classification": "sports",
      "filename": "f1-drift-racer"
    },
    {
      "name": "Stunt Rider",
      "file": "games/sports/stunt-rider.html",
      "classification": "sports",
      "filename": "stunt-rider"
    },
    {
      "name": "Truck Driver: Snowy Roads",
      "file": "games/sports/truck-driver-snowy-roads.html",
      "classification": "sports",
      "filename": "truck-driver-snowy-roads"
    },
    {
      "name": "Jeep Driver",
      "file": "games/sports/jeep-driver.html",
      "classification": "sports",
      "filename": "jeep-driver"
    },
    {
      "name": "Police Real Chase Car Simulator",
      "file": "games/sports/police-real-chase-car-simulator.html",
      "classification": "sports",
      "filename": "police-real-chase-car-simulator"
    },
    {
      "name": "Vehicles Simulator 2",
      "file": "games/sports/vehicles-simulator-2.html",
      "classification": "sports",
      "filename": "vehicles-simulator-2"
    },
    {
      "name": "Car Football",
      "file": "games/sports/car-football.html",
      "classification": "sports",
      "filename": "car-football"
    },
    {
      "name": "Eggy Car",
      "file": "games/sports/eggy-car.html",
      "classification": "sports",
      "filename": "eggy-car"
    },
    {
      "name": "Car Stunt King",
      "file": "games/sports/car-stunt-king.html",
      "classification": "sports",
      "filename": "car-stunt-king"
    },
    {
      "name": "Crazy Parking Fury",
      "file": "games/sports/crazy-parking-fury.html",
      "classification": "sports",
      "filename": "crazy-parking-fury"
    },
    {
      "name": "Drift Fury",
      "file": "games/sports/drift-fury.html",
      "classification": "sports",
      "filename": "drift-fury"
    },
    {
      "name": "GT Cars City Racing",
      "file": "games/sports/gt-cars-city-racing.html",
      "classification": "sports",
      "filename": "gt-cars-city-racing"
    },
    {
      "name": "Taxi Simulator",
      "file": "games/sports/taxi-simulator.html",
      "classification": "sports",
      "filename": "taxi-simulator"
    },
    {
      "name": "ATV Highway Traffic",
      "file": "games/sports/atv-highway-traffic.html",
      "classification": "sports",
      "filename": "atv-highway-traffic"
    },
    {
      "name": "Police Stunt Cars",
      "file": "games/sports/police-stunt-cars.html",
      "classification": "sports",
      "filename": "police-stunt-cars"
    },
    {
      "name": "Cars Simulator",
      "file": "games/sports/cars-simulator.html",
      "classification": "sports",
      "filename": "cars-simulator"
    },
    {
      "name": "Julio Police Cars",
      "file": "games/sports/julio-police-cars.html",
      "classification": "sports",
      "filename": "julio-police-cars"
    },
    {
      "name": "Car Parking",
      "file": "games/sports/car-parking.html",
      "classification": "sports",
      "filename": "car-parking"
    },
    {
      "name": "Police Traffic",
      "file": "games/sports/police-traffic.html",
      "classification": "sports",
      "filename": "police-traffic"
    },
    {
      "name": "Fort Drifter",
      "file": "games/sports/fort-drifter.html",
      "classification": "sports",
      "filename": "fort-drifter"
    },
    {
      "name": "City Car Simulator",
      "file": "games/sports/city-car-simulator.html",
      "classification": "sports",
      "filename": "city-car-simulator"
    },
    {
      "name": "Burnout Drift Hunter",
      "file": "games/sports/burnout-drift-hunter.html",
      "classification": "sports",
      "filename": "burnout-drift-hunter"
    },
    {
      "name": "Highway Racer 2",
      "file": "games/sports/highway-racer-2.html",
      "classification": "sports",
      "filename": "highway-racer-2"
    },
    {
      "name": "Burnout Racers",
      "file": "games/sports/burnout-racers.html",
      "classification": "sports",
      "filename": "burnout-racers"
    },
    {
      "name": "City Stunts",
      "file": "games/sports/city-stunts.html",
      "classification": "sports",
      "filename": "city-stunts"
    },
    {
      "name": "Stunt Simulator",
      "file": "games/sports/stunt-simulator.html",
      "classification": "sports",
      "filename": "stunt-simulator"
    },
    {
      "name": "School Bus",
      "file": "games/sports/school-bus.html",
      "classification": "sports",
      "filename": "school-bus"
    },
    {
      "name": "Monster Truck Mountain Climb",
      "file": "games/sports/monster-truck-mountain-climb.html",
      "classification": "sports",
      "filename": "monster-truck-mountain-climb"
    },
    {
      "name": "Crazy Car Arena",
      "file": "games/sports/crazy-car-arena.html",
      "classification": "sports",
      "filename": "crazy-car-arena"
    },
    {
      "name": "Vegas Crime City",
      "file": "games/sports/vegas-crime-city.html",
      "classification": "sports",
      "filename": "vegas-crime-city"
    },
    {
      "name": "Poly Racing Cars",
      "file": "games/sports/poly-racing-cars.html",
      "classification": "sports",
      "filename": "poly-racing-cars"
    },
    {
      "name": "Offroad Rally",
      "file": "games/sports/offroad-rally.html",
      "classification": "sports",
      "filename": "offroad-rally"
    },
    {
      "name": "Stunt Simulator Multiplayer",
      "file": "games/sports/stunt-simulator-multiplayer.html",
      "classification": "sports",
      "filename": "stunt-simulator-multiplayer"
    },
    {
      "name": "Race Clicker: Drift Max",
      "file": "games/sports/race-clicker-drift-max.html",
      "classification": "sports",
      "filename": "race-clicker-drift-max"
    },
    {
      "name": "Supercars Drift",
      "file": "games/sports/supercars-drift.html",
      "classification": "sports",
      "filename": "supercars-drift"
    },
    {
      "name": "Elite Racing",
      "file": "games/sports/elite-racing.html",
      "classification": "sports",
      "filename": "elite-racing"
    },
    {
      "name": "Rally Champion",
      "file": "games/sports/rally-champion.html",
      "classification": "sports",
      "filename": "rally-champion"
    },
    {
      "name": "Jelly Car Simulator",
      "file": "games/sports/jelly-car-simulator.html",
      "classification": "sports",
      "filename": "jelly-car-simulator"
    },
    {
      "name": "Stunt Simulator 2",
      "file": "games/sports/stunt-simulator-2.html",
      "classification": "sports",
      "filename": "stunt-simulator-2"
    },
    {
      "name": "Mr Racer",
      "file": "games/sports/mr-racer.html",
      "classification": "sports",
      "filename": "mr-racer"
    },
    {
      "name": "Drag Racing Club",
      "file": "games/sports/drag-racing-club.html",
      "classification": "sports",
      "filename": "drag-racing-club"
    },
    {
      "name": "Monster Truck City Parking",
      "file": "games/sports/monster-truck-city-parking.html",
      "classification": "sports",
      "filename": "monster-truck-city-parking"
    },
    {
      "name": "Pixel Driver",
      "file": "games/sports/pixel-driver.html",
      "classification": "sports",
      "filename": "pixel-driver"
    },
    {
      "name": "Super Hero Driving School",
      "file": "games/sports/super-hero-driving-school.html",
      "classification": "sports",
      "filename": "super-hero-driving-school"
    },
    {
      "name": "Egg Car Racing",
      "file": "games/sports/egg-car-racing.html",
      "classification": "sports",
      "filename": "egg-car-racing"
    },
    {
      "name": "Futuristic Racer",
      "file": "games/sports/futuristic-racer.html",
      "classification": "sports",
      "filename": "futuristic-racer"
    },
    {
      "name": "Motorbike Stunt Simulator",
      "file": "games/sports/motorbike-stunt-simulator.html",
      "classification": "sports",
      "filename": "motorbike-stunt-simulator"
    },
    {
      "name": "Moto X3M",
      "file": "games/sports/moto-x3m.html",
      "classification": "sports",
      "filename": "moto-x3m"
    },
    {
      "name": "Vex X3M 2",
      "file": "games/sports/vex-x3m-2.html",
      "classification": "sports",
      "filename": "vex-x3m-2"
    },
    {
      "name": "Motor Tour",
      "file": "games/sports/motor-tour.html",
      "classification": "sports",
      "filename": "motor-tour"
    },
    {
      "name": "Moto X3M Pool Party",
      "file": "games/sports/moto-x3m-pool-party.html",
      "classification": "sports",
      "filename": "moto-x3m-pool-party"
    },
    {
      "name": "Motorbike Traffic",
      "file": "games/sports/motorbike-traffic.html",
      "classification": "sports",
      "filename": "motorbike-traffic"
    },
    {
      "name": "Moto X3M Spooky Land",
      "file": "games/sports/moto-x3m-spooky-land.html",
      "classification": "sports",
      "filename": "moto-x3m-spooky-land"
    },
    {
      "name": "Moto X3M Winter",
      "file": "games/sports/moto-x3m-winter.html",
      "classification": "sports",
      "filename": "moto-x3m-winter"
    },
    {
      "name": "Monster Cars: Ultimate Simulator",
      "file": "games/sports/monster-cars-ultimate-simulator.html",
      "classification": "sports",
      "filename": "monster-cars-ultimate-simulator"
    },
    {
      "name": "Moto Trials",
      "file": "games/sports/moto-trials.html",
      "classification": "sports",
      "filename": "moto-trials"
    },
    {
      "name": "Jet Ski Boat Race",
      "file": "games/sports/jet-ski-boat-race.html",
      "classification": "sports",
      "filename": "jet-ski-boat-race"
    },
    {
      "name": "Crazy Karts",
      "file": "games/sports/crazy-karts.html",
      "classification": "sports",
      "filename": "crazy-karts"
    },
    {
      "name": "Coach Bus Drive Simulator",
      "file": "games/sports/coach-bus-drive-simulator.html",
      "classification": "sports",
      "filename": "coach-bus-drive-simulator"
    },
    {
      "name": "Ultimate Moto",
      "file": "games/sports/ultimate-moto.html",
      "classification": "sports",
      "filename": "ultimate-moto"
    },
    {
      "name": "Shortcut Race",
      "file": "games/sports/shortcut-race.html",
      "classification": "sports",
      "filename": "shortcut-race"
    },
    {
      "name": "Hover Racer Pro",
      "file": "games/sports/hover-racer-pro.html",
      "classification": "sports",
      "filename": "hover-racer-pro"
    },
    {
      "name": "Crazy Moto Racing",
      "file": "games/sports/crazy-moto-racing.html",
      "classification": "sports",
      "filename": "crazy-moto-racing"
    },
    {
      "name": "Horse Rider",
      "file": "games/sports/horse-rider.html",
      "classification": "sports",
      "filename": "horse-rider"
    },
    {
      "name": "Duck Life Battle",
      "file": "games/sports/duck-life-battle.html",
      "classification": "sports",
      "filename": "duck-life-battle"
    },
    {
      "name": "Christmas Monster Truck",
      "file": "games/sports/christmas-monster-truck.html",
      "classification": "sports",
      "filename": "christmas-monster-truck"
    },
    {
      "name": "F1 Racing",
      "file": "games/sports/f1-racing.html",
      "classification": "sports",
      "filename": "f1-racing"
    },
    {
      "name": "Duck Life",
      "file": "games/sports/duck-life.html",
      "classification": "sports",
      "filename": "duck-life"
    },
    {
      "name": "Neon Racer",
      "file": "games/sports/neon-racer.html",
      "classification": "sports",
      "filename": "neon-racer"
    },
    {
      "name": "Duck Life 2",
      "file": "games/sports/duck-life-2.html",
      "classification": "sports",
      "filename": "duck-life-2"
    },
    {
      "name": "Hover Racer",
      "file": "games/sports/hover-racer.html",
      "classification": "sports",
      "filename": "hover-racer"
    },
    {
      "name": "Formula 1 Driver",
      "file": "games/sports/formula-1-driver.html",
      "classification": "sports",
      "filename": "formula-1-driver"
    },
    {
      "name": "Snow Hill Racing",
      "file": "games/sports/snow-hill-racing.html",
      "classification": "sports",
      "filename": "snow-hill-racing"
    },
    {
      "name": "Kart Racing Pro",
      "file": "games/sports/kart-racing-pro.html",
      "classification": "sports",
      "filename": "kart-racing-pro"
    },
    {
      "name": "Powerslide Kart Simulator",
      "file": "games/sports/powerslide-kart-simulator.html",
      "classification": "sports",
      "filename": "powerslide-kart-simulator"
    },
    {
      "name": "Car Rush",
      "file": "games/sports/car-rush.html",
      "classification": "sports",
      "filename": "car-rush"
    }
  ]
};

// 扁平化的游戏列表用于搜索
const ALL_GAMES = [];
for (const [category, games] of Object.entries(GAMES_DATABASE)) {
    if (Array.isArray(games)) {
        games.forEach(game => {
            if (game && game.name) {
                ALL_GAMES.push({
                    ...game,
                    category: game.classification || category
                });
            }
        });
    }
}

console.log('📈 Total games loaded for search:', ALL_GAMES.length);

// 导出数据供搜索系统使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { GAMES_DATABASE, ALL_GAMES };
} else if (typeof window !== 'undefined') {
    window.GAMES_DATABASE = GAMES_DATABASE;
    window.ALL_GAMES = ALL_GAMES;
}
