#!/usr/bin/env node

// Script to generate games_data.js from generated_games.json
const fs = require('fs');

// 读取JSON文件
const jsonPath = './generated_games.json';
const outputPath = './games_data.js';

try {
    console.log('📖 Reading JSON database...');
    const jsonData = fs.readFileSync(jsonPath, 'utf8');
    const gamesData = JSON.parse(jsonData);

    console.log('📊 Found games in categories:');
    Object.keys(gamesData).forEach(category => {
        console.log(`  ${category}: ${gamesData[category].length} games`);
    });

    // 生成JavaScript文件内容
    let jsContent = `// Games data embedded directly in JavaScript
// This file is automatically generated from generated_games.json
// Generated on: ${new Date().toISOString()}
// Total games: ${Object.values(gamesData).reduce((sum, games) => sum + games.length, 0)}

const GAMES_DATABASE = ${JSON.stringify(gamesData, null, 2)};

// 扁平化的游戏列表用于搜索
const ALL_GAMES = [];
for (const [category, games] of Object.entries(GAMES_DATABASE)) {
    if (Array.isArray(games)) {
        games.forEach(game => {
            if (game && game.name) {
                ALL_GAMES.push({
                    ...game,
                    category: game.classification || category
                });
            }
        });
    }
}

console.log('📈 Total games loaded for search:', ALL_GAMES.length);

// 导出数据供搜索系统使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { GAMES_DATABASE, ALL_GAMES };
} else if (typeof window !== 'undefined') {
    window.GAMES_DATABASE = GAMES_DATABASE;
    window.ALL_GAMES = ALL_GAMES;
}
`;

    // 写入文件
    fs.writeFileSync(outputPath, jsContent);
    console.log('✅ Successfully generated games_data.js');
    console.log(`📁 Output file: ${outputPath}`);
    console.log(`📊 Total games included: ${Object.values(gamesData).reduce((sum, games) => sum + games.length, 0)}`);

    // 检查Gold Miner是否包含在内
    let goldMinerFound = false;
    Object.values(gamesData).forEach(games => {
        games.forEach(game => {
            if (game.name && game.name.toLowerCase().includes('gold miner')) {
                console.log(`✅ Found Gold Miner: ${game.name} in ${game.file}`);
                goldMinerFound = true;
            }
        });
    });

    if (!goldMinerFound) {
        console.log('⚠️ Gold Miner not found in the database!');
    }

} catch (error) {
    console.error('❌ Error generating games_data.js:', error);
    process.exit(1);
}